name: Deploy HTML Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH Client
      run: sudo apt-get install -y sshpass

    - name: Setup SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.PROKCD }}
        SERVER_IP: 54.254.204.223
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan 54.254.204.223 >> ~/.ssh/known_hosts

    - name: Copy files to server
      env:
        SERVER_USER: root
        SERVER_IP: 54.254.204.223
        SERVER_DIR: /www/wwwroot/prokcd.run.place
      run: |
        rsync -avz --delete -e "ssh -i ~/.ssh/id_rsa" ./root@54.254.204.223:$SERVER_DIR

    - name: Restart server (optional)
      env:
        SERVER_USER: root
        SERVER_IP: 54.254.204.223
      run: |
        ssh -i ~/.ssh/id_rsa root@54.254.204.223 'sudo systemctl restart your_web_server_service'
